name: Build and Deploy Script
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js with nvm
      uses: actions/setup-node@v2
      with:
        node-version: '16.20.2'

    - name: Use Node.js version with nvm
      run: |
        nvm use 16.20.2
        node --version

    - name: Install Dependencies
      run: npm install

    - name: Build Angular App
      run: npm run build

    - name: Deploy to GitHub Pages
      run: |
        npx angular-cli-ghpages --dir=dist/your-angular-app
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
