name: Build and Auto Deploy Script
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 16.20.2
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Use Node.js version
      run: |
        sudo apt update
        sudo apt install -y nodejs npm
        node --version
        npm --version
        
    - name: Install Angular CLI               
      run: npm install -g @angular/cli
        ng version

    - name: Install Dependencies
      run: npm install

    - name: Add angular-cli-ghpages
      run: npm install -g angular-cli-ghpages

    - name: Build Angular App
      run: npm run build:prod
      
    - name: Deploy to gh pages
      run: |
        npx angular-cli-ghpages --dir=dist/
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
