name: Build and Auto Deploy Script
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CI: true
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.13' # Specify your desired Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build:prod

      - name: Deploy to GitHub Pages
        run: |
              git config --global user.email 'roufraphael@gmail.com'
              git config --global user.name 'raphael-rouf'
              git clone https://github.com/raphael-rouf/my-portfolio.git ${{ github.repository }}
              cd ${{ github.repository }}
              git checkout gh-pages
              cp -r /home/runner/work/my-portfolio/docs/ .
              git add .
              git commit -m "Deploy to GitHub Pages"
              git push https://username:${{ secrets.GH_TOKEN }}@github.com/raphael-rouf/my-portfolio.git
